project:
  type: website
  resources:
    - cv.pdf

website:
  title: "Robin Cole"
  site-url: https://robmarkcole.com
  # navbar:
  #   right:
  #     - text: "Consulting"
  #       href: consulting.html
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false