project:
  type: website

website:
  title: "Robin Cole"
  site-url: https://robmarkcole.com
  navbar:
    right:
      - text: "Services"
        href: services.html
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false